##########################################################################
#
# - Main playbook for creating a volume, qtree and volume protection SnapMirror
# 
#
# 
# Alexey Mikhaylov
# NetApp Deutschland GmbH
# Professional Services 2024
##########################################################################
---
- name: "Create: volume, qtree, export_policy, destination volume, snapmirror"
  hosts: localhost
  become: false
  gather_facts: false
  #environment:
  #  no_proxy: 127.0.0.1, localhost
  vars_files:
    - "vars/customers/bper/defaults.yml"
    - "vars/customers/bper/local.yml"
   # BPER PROD:
   # - "vars/customers/bper/inventory.yml"
   # NetApp lab:
    - "vars/customers/bper/inventory_lab_test.yml"
   # BPER lab:
   # - "vars/customers/bper/inventory_bper_lab.yml"
  vars:
    qlogname: "test_create_v_q_ep.bper"

  tasks:
    # Setup credentials
    - include_role:
        name: bper/facts
      vars:
        qtask: credentials

    # Validate input variables
    - include_role:
        name: bper/facts
      vars:
        qtask: input_validation

    # Prepare facts (Ex.: FUSn)
    - include_role:
        name: bper/facts
      vars:
        qtask: prepare_facts
    
    - debug: var=vars_local

    # Check inventory SVMs svailability
    - include_role:
        name: bper/logic
      vars:
        qtask: 00_preflight_check

    # Check if volume already exists and set new volume name incerementing by 1
    - include_role:
        name: bper/logic
      vars:
        qtask: 01_preflight_setup
    
    - debug: var=vars_local
    
    # Find suitable source SVM
    - include_role:
        name: bper/logic
      vars:
        qtask: 02_source_setup

    - debug: var=vars_local
    
    # Find suitable destination vault SVM
    - include_role:
        name: bper/logic
      vars:
        qtask: 03_vault_setup

    # Collect export policy facts variables
    - include_role:
        name: ontap/export_policy
      vars:
        qtask: facts
        qchild: source

    # Collect snapmirror facts variables
    - include_role:
        name: ontap/snapmirror
      vars:
        qtask: facts

########## debug + dryrun
    - debug: var=vars_local
    - name: Dryrun exit
      when: input_dryrun | bool
      block:
        #- debug: var=vars_local
        - debug:
            msg: "Data collection completed. Dryrun exit."
        - meta: end_play
########## debug end
    
########### CREATE STEP 1
# no block/rescue when creating source volume since if it wasn't created - there is nothing to rollback
    - block: 
      - include_role:
          name: ontap/volume
        vars:
          qtask: facts
          qchild: source

      - include_role:
          name: ontap/volume
        vars:
          qtask: create
          qchild: source
      rescue:
      - debug:
          msg: "Source volume create task failed. Created objects will be deleted."
      
      - include_role:
          name: ontap/volume
        vars:
          qtask: facts
          qchild: source

      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
          qchild: source
      
      - meta: end_play

########### CREATE STEP 2
# collect source volume qtree facts and trying to create
# otherwise we rollback source volume creation
    - block:      
      - include_role:
          name: ontap/qtree
        vars:
          qtask: facts
          qchild: source

      - include_role:
          name: ontap/qtree
        vars:
          qtask: create
          qchild: source
      rescue:
      - debug:
          msg: "Qtree Create task failed. Created objects will be deleted."

      - include_role:
          name: ontap/volume
        vars:
          qtask: facts
          qchild: source

      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
          qchild: source
      
      - meta: end_play

########### CREATE STEP 3
# collect destination volume facts and trying to create
# otherwise we rollback source volume and qtree creation
    - block:
      - include_role:
          name: ontap/volume
        vars:
          qtask: facts
          qchild: destination

      - include_role:
          name: ontap/volume
        vars:
          qtask: create
          qchild: destination
      rescue:
      - debug:
          msg: "Vault volume create task failed. Created objects will be deleted."
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
          qchild: destination
      - include_role:
          name: ontap/qtree
        vars:
          qtask: facts
          qchild: source
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
          qchild: source
      
      - meta: end_play

########### CREATE STEP 4
# create export policy and rules
# otherwise we rollback source volume, qtree and destination volume creation
    - block:
      - include_role: 
          name: ontap/export_policy
        vars:
          qtask: create
          qchild: source
      rescue:
      - debug:
          msg: "Export policy Create task failed. Created objects will be deleted."
      - include_role:
          name: ontap/qtree
        vars:
          qtask: delete
          qchild: source
      # re-collecting facts to setup values for active svm/volume values       
      - include_role:
          name: ontap/volume
        vars:
          qtask: facts
          qchild: source
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
          qchild: source

      - meta: end_play

########### CREATE STEP 5
# create snapmirror relationship
# otherwise we rollback source volume, qtree, destination volume and export policy creation
    - block:
      - include_role:
          name: ontap/snapmirror
        vars:
          qtask: create
      rescue:
      - debug:
          msg: "Snapmirror create task failed. Created objects will be deleted."
      - include_role:
          name: ontap/snapmirror
        vars:
          qtask: delete
          qchild: source
      - include_role:
          name: ontap/qtree
        vars:
          qtask: delete
          qchild: source
      - include_role: 
          name: ontap/export_policy
        vars:
          qtask: delete
          qchild: source
      # re-collecting facts to setup values for active svm/volume values       
      - include_role:
          name: ontap/volume
        vars:
          qtask: facts
          qchild: source
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
          qchild: source
      # re-collecting facts to setup values for active svm/volume values  
      - include_role:
          name: ontap/volume
        vars:
          qtask: facts
          qchild: destination
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
          qchild: destination
      
      - meta: end_play

...
