##########################################################################
#
# - Main playbook for creating a volume, qtree and volume protection SnapMirror
# 
#
# 
# Alexey Mikhaylov
# NetApp Deutschland GmbH
# Professional Services 2024
##########################################################################
---
- name: "Create volume and qtree"
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - "vars/customers/bper/defaults.yml"
    - "vars/customers/bper/local.yml"
    - "vars/customers/bper/inventory.yml"
    - "vars/customers/bper/inventory_lab_test.yml"
  vars:
    qlogname: "test_create_v_q_ep.muccbc"

  tasks:
    - include_role:
        name: bper/facts
      vars:
        qtask: credentials
    - include_role:
        name: bper/facts
      vars:
        qtask: input_validation
    - include_role:
        name: bper/facts
      vars:
        qtask: prepare_facts
    - include_role:
        name: bper/logic
      vars:
        qtask: volume_check
    - include_role:
        name: bper/logic
      vars:
        qtask: find_svm
    - include_role:
        name: bper/logic
      vars:
        qtask: find_vault_svm
    - include_role:
        name: ontap/volume
      vars:
        qtask: facts
    - include_role:
        name: ontap/qtree
      vars:
        qtask: facts
    - include_role:
        name: ontap/export_policy
      vars:
        qtask: facts
    - include_role:
        name: ontap/snapmirror
      vars:
        qtask: facts
    - include_role:
        name: ontap/volume
      vars:
        qtask: create

########### CREATE
    - block:      
      - include_role:
          name: ontap/qtree
        vars:
          qtask: create
      rescue:
      - debug:
          msg: "Qtree Create task failed"
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
    
    - block:
      - include_role: 
          name: ontap/export_policy
        vars:
          qtask: create
      rescue:
      - debug:
          msg: "Export policy Create task failed"
      - include_role:
          name: ontap/qtree
        vars:
          qtask: delete
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete
      
    - block:
      - include_role:
          name: ontap/snapmirror
        vars:
          qtask: create_destination
      rescue:
      - debug:
          msg: "Snapmirror create task failed"
      - include_role:
          name: ontap/snapmirror
        vars:
          qtask: delete
      - include_role:
          name: ontap/qtree
        vars:
          qtask: delete
      - include_role:
          name: ontap/volume
        vars:
          qtask: delete 
    
    



  # roles:
  #   - { role: bper/facts, qtask: credentials }
  #   - { role: bper/facts, qtask: input_validation }
  #   - { role: bper/facts, qtask: prepare_facts }
  #   - { role: bper/logic, qtask: volume_check }
    
  #   - { role: bper/logic, qtask: find_svm }
  #   - { role: bper/logic, qtask: find_vault_svm }

  #   - { role: ontap/volume, qtask: facts }
  #   - { role: ontap/volume, qtask: create }
  #   - { role: ontap/qtree, qtask: facts }
  #   - { role: ontap/qtree, qtask: create }
    
  #   - { role: ontap/export_policy, qtask: facts }
  #   - { role: ontap/export_policy, qtask: create }
    

  #   - { role: ontap/snapmirror, qtask: facts }
  #   - { role: ontap/snapmirror, qtask: create_destination }

...