- hosts: localhost
  gather_facts: false
  collections:
    - netappps.maf
    - netappps.ontap
    - netappps.bper
  tasks:
    - ansible.builtin.include_role:
        name: netappps.bper.facts
      vars:
        qtask: credentials
