##########################################################################
#
# - check for existing volumes
# 
#
# 
# Alexey Mikhaylov
# NetApp Deutschland GmbH
# Professional Services 2024
##########################################################################
---
- name: "Volume existance check"
  block:
    - name: Set cluster credentials
      ansible.builtin.set_fact:
        auth: &auth
          hostname:        "{{ svm.cluster_mgmt | default(omit) }}"
          username:        "{{ ontap_username | default(omit) }}"
          password:        "{{ ontap_password | default(omit) }}"
          validate_certs:  "{{ auth_rest_validate_certs | default(false) }}"
          use_rest:        always
          use_python_keys: true
      no_log: true

    - name: Reducing inventory for volume lookup 
      ansible.builtin.set_fact:
        reduced_inventory: "{{ reduced_hosts | default([]) + [{'cluster_mgmt': item.cluster_mgmt}] }}"
      loop: "{{ inventory_svms_mcc.hosts }}"

    - debug: var=reduced_inventory
    
    - name: Collecting existing volumes on all clusters against volume "{{ vars_local.volume.name }}"
      netapp.ontap.na_ontap_rest_info:
        <<: *auth
        gather_subset:
          - volume_info
        parameters:
          name: "{{ vars_local.volume.name }}"
        hostname: "{{ svm.cluster_mgmt }}"
      register: existing_vols
      loop: "{{ reduced_inventory | unique}}"
      loop_control:
        loop_var: svm

    - name: Check clusters output for volume "{{ vars_local.volume.name }}"
      ansible.builtin.fail:
        msg: "Volume {{ vars_local.volume.name }} already exists on cluster"
      when: item.ontap_info.storage_volumes.num_records > 0
      loop: "{{ existing_vols.results }}"    
    
    - debug: var=existing_vols.results
    
  when: inventory_svms_mcc.keys() | length > 0
...